version: 2
updates:
- package-ecosystem: "npm"
  
  schedule:
    interval: "daily"
  groups:
    monthly-batch:
      group-by: dependency-name
      patterns:Expand comment
        - "*"
- package-ecosystem: action
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
